#!/usr/bin/env bash

# OPTIONS:
#   --tracks-operation= | -t=opt1,opt2,... @required(conflicts with --structure-operation/-s)
#   --structure-operation= | -s=opt1,opt2,... @required(conflicts with --tracks-operation/-t)
#   --destination "directory" | -d "directory"  @optional
# EXAMPLES:
#   audioxif --tracks-operation=opt1,opt2 <origin_directory>
#   audioxif <origin_directory> --structure-operation=opt1,opt2 --destination <destination_directory>
#   audioxif -d <destination_directory> <origin_directory> -t=opt1,opt2
#   audioxif <origin_directory> -s=opt1,opt2
#   audioxif --tracks-operation=\
##  opt1,\
##  opt2,\
##  opt3

echo "AUDIOXIF SWISS-KNIFE"
NO_PROMPTS='false'
ORIGIN='.'
INDEX=0
UNSAFE_FILE_CHARS_KILLER='[\/\\:*?"<>|]' # Identifica `chars` não aceitos em arquivos para que possam ser substituidos.
EXTENSIONS="mp3 flac m4a ogg opus wma"
TRACKS=()
ARGS=$(echo $@ | tr -s ' ')
read -ra ARGS_DIGESTER <<<"$ARGS"
while [ -n "${ARGS_DIGESTER[$INDEX]}" ]; do
    ARG=${ARGS_DIGESTER[$INDEX]}
    case "$ARG" in
    -s=* | --structure-operation=*)
        if [ "${TRACKS_OPS:-}" ]; then
            echo "ERROR: tracks operation was declared! Tracks and structure operations cannot run together."
            exit 1
        fi
        IFS=',' read -ra STRUCTURE_OPS <<<"$(echo "${ARGS_DIGESTER[$ARGD_INDEX]}" | sed 's/^[^=]*=//')"
        ;;
    -t=* | --tracks-operation=*)
        if [ "${STRUCTURE_OPS:-}" ]; then
            echo "ERROR: structure operation was declared! Tracks and structure operations cannot run together."
            exit 1
        fi
        IFS=',' read -ra TRACKS_OPS <<<"$(echo "${ARGS_DIGESTER[$ARGD_INDEX]}" | sed 's/^[^=]*=//')"
        ;;
    -d | --destination)
        ((INDEX++))
        POST_DEST_DIGEST_INDEX=$INDEX # LATER: Discover a way of enabling entering --copy and --move args between --destination and --destination's path
        ARG=${ARGS_DIGESTER[$INDEX]}
        if [ -d "$ARG" ]; then
            DESTINATION_PATH="$ARG"
            DESTINATION_TRANSPORT_METHOD=${DESTINATION_TRANSPORT_METHOD:-'move'}
        else
            case "$ARG" in
            -c | --copy)
                echo "ERROR: -c/--copy argument must be declared before -d/--destination or after -d/--destination path!"
                ;;
            -m | --move)
                echo "ERROR: -m/--move argument must be declared before -d/--destination or after -d/--destination path!"
                ;;
            *)
                echo "ERROR: -d/--destination argument was declared without a path!"
                ;;
            esac
            exit
        fi
        ;;
    -m | --move) # Default destination transport method, is a meta-argument, only purpose is for clarification in scripts.
        DESTINATION_TRANSPORT_METHOD='move'
        ;;
    -c | --copy)
        DESTINATION_TRANSPORT_METHOD='copy'
        ;;
    -y | --assume-yes)
        NO_PROMPTS='true'
        ;;
    *)
        if [ -d "$ARG" -a "$ORIGIN" = '.' ]; then
            ORIGIN="$ARG"
        else
            echo -e "ERROR: Additonal unrecognized argument was declared! \nSee audioxif --help for guidance."
            exit 1
        fi
        ;;
    esac
    ((INDEX++))
done
if ! [ "${STRUCTURE_OPS:-}" -o "${TRACKS_OPS:-}" ]; then
    echo "No operation declared!"
    exit
fi
ORIGIN=$(realpath $ORIGIN)
if [ "${DESTINATION_PATH:-}" ]; then
    DESTINATION_PATH=$(realpath $DESTINATION_PATH)
    echo "DESTINATION is: $DESTINATION_PATH"
    echo "DESTINATION transport method is: $DESTINATION_TRANSPORT_METHOD"
    case "$DESTINATION_TRANSPORT_METHOD" in
    move)
        dtmethod() {
            mv $@
        }
        ;;
    copy)
        dtmethod() {
            cp -ar $@
        }
        ;;
    esac
fi
INDEX=0
echo "ORIGIN is: $ORIGIN"
if [ "$NO_PROMPTS" == 'false' ]; then
    while [[ true ]]; do
        echo "Is info above correct? [Y/n]"
        read -rp 'Answer: ' CORASWR
        case "$CORASWR" in
        [yY] | [yY]es)
            echo Proceeding...
            break
            ;;
        [nN] | [nN]o)
            echo Exiting...
            exit 0
            ;;
        *)
            echo "Answer with y/yes or n/no."
            ;;
        esac

    done
fi

# OPTS
TARGET=${ORIGIN:-.}
for EXTENSION in $EXTENSIONS; do
    mapfile -t -O "${#TRACKS[@]}" TRACKS < <(find "$TARGET" -iname "*.$EXTENSION" | sort)
done

if [ "${STRUCTURE_OPS:-}" ]; then
    while [ -n "${STRUCTURE_OPS[$INDEX]}" ]; do
        OPT=${STRUCTURE_OPS[$INDEX]}
        case "$OPT" in
        track_positioner)
            source "./lib/structure/tracks position in album.sh "
            # Comment:
            # Read the Track number exif data from the audio file
            # and adds it to start of the a audio file's name.
            ;;
        *)
            echo -e "ERROR: $OPT is an unrecognized option. \nExiting..."
            exit 1
            ;;
        esac
    done
elif [ "${TRACKS_OPS:-}" ]; then
    while [ -n "${TRACKS_OPS[$INDEX]}" ]; do
        OPT=${TRACKS_OPS[$INDEX]}
        case "$OPT" in
        multiple_artists)
            source "./lib/tracks/multiple artists.sh"
            # Comment:
            # Make a single ARTIST that contains more than one
            # artist in a multiple ARTISTS for the 'coadjuvants artists',
            # intended for Navidrome use.
            ;;
        set_album_name)
            source "./lib/tracks/add unset album.sh"
            # Comment:
            # Adiciona o valor da tag ALBUM caso ela
            # não exista, requerimento: valor da tag
            # TITLE
            ;;
        trim_artwork)
            source "./lib/tracks/trim track artwork.sh"
            # Comment:
            # Trim disproporcional artwork's/coverart's ratio
            # to 1:1, which is the standart.
            ;;
        *)
            echo -e "ERROR: $OPT is an unrecognized option. \nExiting..."
            exit 1
            ;;
        esac
    done
fi
if [ "${DESTINATION_PATH:-}" ]; then
    dtmethod "$ORIGIN"/* "$DESTINATION_PATH"/
fi
