#!/usr/bin/env bash

set -euo pipefail
trap 'echo -e "[ FATAL ] Error in ${BASH_SOURCE[0]} at line ${LINENO}: ${BASH_COMMAND} \n\n[ EXIT ${?} ]" >&2' ERR
# OPTIONS:
#   --metadata-operation= | -m=opt1,opt2,... @required(conflicts with --structure-operation/-s)
#   --structure-operation= | -s=opt1,opt2,... @required(conflicts with --metadata-operation/-m)
#   --destination "directory" | -d "directory"  @optional
# EXAMPLES:
#   metaudio --metadata-operation=opt1,opt2 <origin_directory>
#   metaudio <origin_directory> --structure-operation=opt1,opt2 --destination <destination_directory>
#   metaudio -d <destination_directory> <origin_directory> -m=opt1,opt2
#   metaudio <origin_directory> -s=opt1,opt2

printf ' __  __      _                     _ _       
|  \/  |    | |     /\            | (_)      
| \  / | ___| |_   /  \  _   _  __| |_  ___  
| |\/| |/ _ \ __| / /\ \| | | |/ _` | |/ _ \ 
| |  | |  __/ |_ / ____ \ |_| | (_| | | (_) |
|_|  |_|\___|\__/_/    \_\__,_|\__,_|_|\___/ 
                                             
'

# Resolve the absolute path of the directory containing this script,
# regardless of where it is invoked from.
SHPWD=$(realpath "$0")
SHPWD=$(dirname "$SHPWD")
NO_PROMPTS='false'
ORIGIN='.'
UNSAFE_FILE_CHARS_KILLER='[\/\\:*?"<>|]' # Identifica `chars` não aceitos em arquivos para que possam ser substituidos.
EXTENSIONS="flac m4a"                    # No Futuro: mp3 ogg opus wma
INDEX=0
ARGS_DIGESTER=("$@")

# Check depedencies
source "$SHPWD/lib/check-dependencies.sh"
NULLIFIER=$(openssl rand -hex 5)_null_$(openssl rand -hex 5)

while [ "${ARGS_DIGESTER[$INDEX]:-$NULLIFIER}" != "$NULLIFIER" ]; do
    ARG="${ARGS_DIGESTER[$INDEX]}"
    case "$ARG" in
    -s=* | --structure-operation=*)
        if [ "${METADATA_OPS:-}" ]; then
            echo "ERROR: metadata operation was declared! Tracks and structure operations cannot run together."
            exit 2
        elif [ ${ARG#*=} == 'help' ]; then
            cat "$SHPWD/docs/structure_ops-help.txt"
            exit 0
        fi
        IFS=',' read -ra STRUCTURE_OPS <<<"${ARG#*=}"
        ;;
    -m=* | --metadata-operation=*)
        if [ "${STRUCTURE_OPS:-}" ]; then
            echo "ERROR: structure operation was declared! Tracks and structure operations cannot run together."
            exit 2
        elif [ ${ARG#*=} == 'help' ]; then
            cat "$SHPWD/docs/metadata_ops-help.txt"
            exit 0
        fi
        IFS=',' read -ra METADATA_OPS <<<"${ARG#*=}"
        ;;
    -d | --destination)
        INDEX=$((INDEX + 1))
        POST_DEST_DIGEST_INDEX=$INDEX # TODO: Discover a way of enabling entering --copy and --move args between --destination and --destination's path
        ARG=${ARGS_DIGESTER[$INDEX]}
        if [ -d "$ARG" ]; then
            DESTINATION_PATH="$ARG"
            DESTINATION_TRANSPORT_METHOD=${DESTINATION_TRANSPORT_METHOD:-'move'}
        else
            case "$ARG" in
            -c | --copy)
                echo "ERROR: -c/--copy argument must be declared before -d/--destination or after -d/--destination path!"
                ;;
            -m | --move)
                echo "ERROR: -m/--move argument must be declared before -d/--destination or after -d/--destination path!"
                ;;
            *)
                echo "ERROR: -d/--destination argument was declared without a path!"
                ;;
            esac
            exit 2
        fi
        ;;
    -m | --move) # Default destination transport method, is a meta-argument, only purpose is for clarification in scripts.
        DESTINATION_TRANSPORT_METHOD='move'
        ;;
    -c | --copy)
        DESTINATION_TRANSPORT_METHOD='copy'
        ;;
    -y | --assume-yes)
        NO_PROMPTS='true'
        ;;
    -h | --help)
        cat "$SHPWD/docs/help.txt"
        exit 0
        ;;
    *)
        if [ -d "$ARG" -a "$ORIGIN" = '.' ]; then
            ORIGIN="$ARG"
        else
            echo -e "ERROR: $ARG is an additonal unrecognized argument was declared! \nSee audioxif --help for guidance."
            exit 2
        fi
        ;;
    esac
    INDEX=$((INDEX + 1))
done
if ! [ "${STRUCTURE_OPS:-}" -o "${METADATA_OPS:-}" ]; then
    echo "No operation declared!"
    exit 2
fi
ORIGIN=$(realpath "$ORIGIN")
if [ "${DESTINATION_PATH:-}" ]; then
    DESTINATION_PATH=$(realpath "$DESTINATION_PATH")
    echo "DESTINATION is: $DESTINATION_PATH"
    echo "DESTINATION transport method is: $DESTINATION_TRANSPORT_METHOD"
    case "$DESTINATION_TRANSPORT_METHOD" in
    move)
        dtmethod() {
            cp -ar "$1" "$2" &&
                rm -rf "$1"
        }
        ;;
    copy)
        dtmethod() {
            cp -ar "$@"
        }
        ;;
    esac
fi
INDEX=0
echo "ORIGIN is: $ORIGIN"
if [ "$NO_PROMPTS" == 'false' ]; then
    while [ true ]; do
        echo "Is info above correct? [Y/n]"
        read -rp 'Answer: ' CORASWR
        case "$CORASWR" in
        [yY] | [yY]es)
            echo Proceeding...
            break
            ;;
        [nN] | [nN]o)
            echo Exiting...
            exit 0
            ;;
        *)
            echo "Answer with y/yes or n/no."
            ;;
        esac

    done
fi

# OPTS

if [ "${STRUCTURE_OPS:-}" ]; then
    while [ "${STRUCTURE_OPS[$INDEX]:-$NULLIFIER}" != "$NULLIFIER" ]; do
        TRACKS=()
        for EXTENSION in $EXTENSIONS; do
            mapfile -t -O "${#TRACKS[@]}" TRACKS < <(find "$ORIGIN" -iname "*.$EXTENSION" | sort)
        done
        OPT="${STRUCTURE_OPS[$INDEX]}"
        case "$OPT" in
        track_positioner)
            source "$SHPWD/lib/structure/tracks_position_in_album.sh"
            ;;
        sort_album_type)
            source "$SHPWD/lib/structure/albums_sort_by_track_count.sh"
            ;;
        artist_base_structure)
            source "$SHPWD/lib/structure/artist_base_structure.sh"
            ;;
        album_folder_sync)
            source "$SHPWD/lib/structure/album_folder_sync.sh"
            ;;
        *)
            echo -e "ERROR: $OPT is an unrecognized option. \nExiting..."
            exit 2
            ;;
        esac
        INDEX=$((INDEX + 1))
    done
elif [ "${METADATA_OPS:-}" ]; then
    TRACKS=()
    for EXTENSION in $EXTENSIONS; do
        mapfile -t -O "${#TRACKS[@]}" TRACKS < <(find "$ORIGIN" -iname "*.$EXTENSION" | sort)
    done
    while [ "${METADATA_OPS[$INDEX]:-$NULLIFIER}" != "$NULLIFIER" ]; do
        OPT="${METADATA_OPS[$INDEX]}"
        case "$OPT" in
        multiple_artists)
            source "$SHPWD/lib/tracks/multiple_artists.sh"
            ;;
        set_album_name)
            source "$SHPWD/lib/tracks/add_unset_album.sh"
            ;;
        trim_artwork)
            source "$SHPWD/lib/tracks/trim_track_artwork.sh"
            ;;
        set_album_artist)
            source "$SHPWD/lib/tracks/set_album_artist.sh"
            ;;
        *)
            echo -e "ERROR: $OPT is an unrecognized option. \nExiting..."
            exit 2
            ;;
        esac
        INDEX=$((INDEX + 1))
    done
fi

if [ "${DESTINATION_PATH:-}" -a "$DESTINATION_TRANSPORT_METHOD" = 'move' ]; then
    for ITEM in "$ORIGIN"/*; do
        dtmethod "$ITEM" "$DESTINATION_PATH"/
    done
elif [ "${DESTINATION_PATH:-}" -a "$DESTINATION_TRANSPORT_METHOD" = 'copy' ]; then
    dtmethod "$ORIGIN"/* "$DESTINATION_PATH"/
fi
